config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'orders#index'
  resources :products, only: [:index]
  put 'orders/:id/confirm_order', to: 'orders#confirm_order', as: :confirm_order
  resources :orders, except: [:index] do
    scope module: :orders do
      resources :order_items, only: [:create, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :delete_all

  def total_amount
    order_items.map { |i| i.bill_amount }.sum
  end

  def bill_amount
    total_amount - coupon_discount
  end

  def coupon_discount
    if coupon_code == 'ORDER10'
      total_amount * 0.10
    else
      0
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true
  validates_uniqueness_of :product_id, scope: [:order_id]
  before_create :set_product_details
  before_save :set_discount

  def bill_amount
    amount - discount
  end


  def set_product_details
    self.product_name = product.name
    self.rate = product.price
    set_amount
  end

  def set_discount
    set_amount
    combo = product.combo
    if quantity >= combo && combo > 0
      self.discount = (quantity / combo).to_i * product.discount
    end
  end

  def set_amount
    self.amount = rate * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders/order_items_controller.rb
class Orders::OrderItemsController < ApplicationController
  before_action :set_order
  before_action :set_order_item, only: [:destroy, :update]

  def create
    @order_item = @order.order_items.create(order_item_params)
    if @order_item.errors.blank?
      redirect_to edit_order_path(@order)
    end
  end

  def update
    @order_item.update(order_item_params)
    redirect_to edit_order_path(@order)
  end

  def destroy
    @order_item.destroy
    redirect_to edit_order_path(@order)
  end

  private

  def set_order
    @order = Order.find_by_id params[:order_id]
  end

  def set_order_item
    @order_item = @order.order_items.find_by_id params[:id]
  end

  def order_item_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, except: [:index, :create]
  def index
    @orders = Order.order(created_at: :desc)
  end

  def create
    @order = Order.create
    redirect_to edit_order_path(@order)
  end

  def edit

  end

  def show

  end

  def update
    @order.update(order_params)
    redirect_to order_path(@order)
  end

  def destroy
    @order.destroy
    redirect_to root_path
  end

  def confirm_order
    @order.update(confirm_order: true, date_of_order: Date.today)
    redirect_to order_path(@order)
  end

  private

  def set_order
    @order = Order.find_by_id params[:id]
  end

  def order_params
    params.require(:order).permit(:coupon_code)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders/order_items_helper.rb
module Orders::OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supermarket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container is-fluid">
    <%= yield %>
  </div>
  </body>
</html>

app/views/orders/edit.html.erb
<div class="content">
  <h3>Supermarket - buy groceries here</h3>
  <div style="width: 50%;margin: 10px 0;">
    <%= form_with model: [@order, OrderItem.new], data: { remote: true } do |f| %>
      <div class="field">
        <div class="control">
          <div class="select">
            <%= f.select :product_id, options_from_collection_for_select(Product.all, :id, :name, nil) %>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.number_field :quantity, class: 'input' %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.submit 'Add', class: 'button is-success' %>
        </div>
      </div>
    <% end %>
  </div>

  <table>
    <thead>
    <tr>
      <th>Item</th>
      <th>Rate</th>
      <th style="width: 30%;">Quantity</th>
      <th style="width: 5%;"></th>
    </tr>
    </thead>
    <tbody>
    <% @order.order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.product_name %></td>
        <td><%= order_item.rate %></td>
        <td>
          <%= form_with model: [@order, order_item] do |f| %>
            <div class="field is-grouped">
              <div class="control">
                <%= f.number_field :quantity, class: 'input' %>
              </div>
              <div class="control">
                <%= f.submit 'save', class: 'button' %>
              </div>
            </div>
          <% end %>
        </td>
        <td>
          <%= link_to 'Remove', order_order_item_path(order_item), method: :delete %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="field is-grouped" style="margin: 10px 0;">
    <div class="control">
      <%= link_to 'Cancel', order_path(@order), method: :delete, class: 'button' %>
    </div>
    <div class="control">
      <%= link_to 'Confirm selection', order_path(@order), class: 'button is-success' %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="content">
  <h3>Supermarket - buy groceries here</h3>
  <div class="field">
    <div class="control">
      <%= button_to "New Order", orders_path, class: 'button is-success' %>
    </div>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th>S.no</th>
      <th>Date of order</th>
      <th>Order value</th>
      <th>Details</th>
    </tr>
    </thead>
    <tbody>
    <% @orders.each_with_index do |order, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= order.date_of_order %></td>
        <td><%= order.bill_amount %></td>
        <td><%= link_to 'Click to summary', order_path(order) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/orders/order_items/create.js.erb
<% if @order_item.errors.present? %>
alert('<%= @order_item.errors.full_messages.to_sentence %>')
<%end %>

app/views/orders/show.html.erb
<div class="content">
  <h3>Order summary</h3>
  <%= link_to 'Home', root_path %>
  <table>
    <thead>
    <tr>
      <th>S.no</th>
      <th>Item</th>
      <th class="has-text-right">Rate</th>
      <th class="has-text-right">Qty</th>
      <th class="has-text-right">Amount</th>
      <th class="has-text-right">Discount</th>
      <th class="has-text-right">BillAmount</th>
    </tr>
    </thead>
    <tbody>
    <% @order.order_items.each_with_index do |order_item, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= order_item.product_name %></td>
        <td class="has-text-right"><%= order_item.rate %></td>
        <td class="has-text-right"><%= order_item.quantity %></td>
        <td class="has-text-right"><%= order_item.amount %></td>
        <td class="has-text-right"><%= order_item.discount %></td>
        <td class="has-text-right"><%= order_item.bill_amount %></td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="5"></td>
      <td class="has-text-right has-text-weight-bold">Total</td>
      <td class="has-text-right has-text-weight-bold"><%= @order.total_amount %></td>
    </tr>
    </tfoot>
  </table>

  <div class="columns">
    <div class="column">
      <%= form_with model: [@order] do |f| %>
        <div class="field">
          <label class="label">Coupon Code</label>
          <div class="control">
            <%= f.text_field :coupon_code, class: 'input' %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= f.submit 'Apply coupon', class: 'button is-info' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="column">
      <table>
        <tbody>
        <tr>
          <td>Coupon discount</td>
          <td><%= @order.coupon_discount %></td>
        </tr>
        <tr>
          <td>Order amount</td>
          <td><%= @order.bill_amount %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="field is-grouped" style="margin: 10px 0;">
    <% unless @order.confirm_order %>
      <div class="control">
        <%= link_to 'Modify order', edit_order_path(@order), class: 'button' %>
      </div>
    <% end %>

    <div class="control">
      <%= link_to 'Confirm order', confirm_order_path(@order), method: :put, class: 'button is-success' %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="content">
  <h3>List of Products</h3>
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Combo</th>
      <th>Discount</th>
    </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.combo %></td>
        <td><%= product.discount %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>